version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "technicianapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13xtti8er3wuy"
s3_prefix = "technicianapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
